url: "https://adamcarlile.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Adam Carlile: Technical Leader" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-postcss-v2
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-spaceship
  - jekyll-gfm-admonitions

jekyll-archives:
  enabled:
    - year
    - tags
    - category
  layout: blog/archive
  permalinks:
    year: /blog/:year/
    tag: /blog/tags/:name/
    category: /blog/category/:name/

postcss:
  cache: false

exclude:
 - package-lock.json
 - package.json
 - postcss.config.js
 - tailwind.config.js

permalink: /blog/:year/:title:output_ext

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
      start_line: 1

navigation:
  - title: "Home"
    url: "/"
    icon: "fa-solid fa-house"
  - title: "Blog"
    url: "/blog/"
    icon: "fa-solid fa-blog"

social_links:
  - platform: "GitHub"
    url: "https://github.com/adamcarlile"
    icon: "fa-brands fa-github"
    external: true
    title: "Visit my GitHub profile"
    bg_class: "bg-gray-700 hover:bg-gray-600"
  - platform: "LinkedIn"
    url: "https://www.linkedin.com/in/adam-carlile-191a4215/"
    icon: "fa-brands fa-linkedin"
    external: true
    title: "Visit my LinkedIn profile"
    bg_class: "bg-blue-600 hover:bg-blue-500"
  - platform: "X"
    url: "https://x.com/frozenproduce"
    icon: "fa-brands fa-x-twitter"
    external: true
    title: "Visit my X profile"
    bg_class: "bg-gray-800 hover:bg-gray-700"